### ISSUE TITLE
[BUG] [+Plugin] Few bugs

### ISSUE THREAD

**Issue by vdbhb59** [LeedRSS/Leed#506] opened 2023-06-07 11:11 UTC
I am using the latest dev release (1.13.0) and upon deployment, I have found couple of bugs/issues:

1. The URL has a random number always. Example: https://myinstanceurl/#2099 (random number here)
2. The side column loads once and then goes away/vanishes. This happens with Fleexed plugin (see snap 01)
3. The same plugin causes "identified as username" details to get overlayed by the leed icon (see snap 01)
4. When I disable the Fleexed plugin, the "Menu" button does not get clicked (see snap 02)
5. ePub plugin does not work. When enabled, and when I select any option within the plugin, the page refreshes and goes white/blank. There is no error_log entry for this as well, so not sure how to give you any details.
6. The favicon does not load for the deployment. See last snap.

![Leed_Bugs_01](https://github.com/LeedRSS/Leed/assets/60728004/834896bf-bf03-4762-95de-da6571829a11)
Image: Leed_Bugs_01
![Leed_Bugs_02](https://github.com/LeedRSS/Leed/assets/60728004/c2e62baf-b839-4244-8dd7-e2cb197279b8)
Image: Leed_Bugs_02
![image](https://github.com/LeedRSS/Leed/assets/60728004/efc4ae37-e6f6-4b70-963f-c7ca210ed7e4)
Image: Favicon not loading on deployed site.

**Comment by Simounet** [comment] 2023-06-07 16:24
I'll reply in this thread but it's easier for us that you open a new bug for each question. Plus, it seems like it's mostly "bugs" on https://github.com/Leed-market/fleexed, a long time, not updated theme.
Did you try https://github.com/Leed-market/LeedVibes? Kind of the same layout but updated regularly (by myself 😁).



1. The URL has a random number always. Example: https://myinstanceurl/#2099 (random number here)
It's not a bug, it's a "feature". It's the last item id, used to scroll to the content on mobile.

3. The side column loads once and then goes away/vanishes. This happens with Fleexed plugin (see snap 01)
Which browser are you using? I can't reproduce this behavior. And you also give your enabled plugins list?

4. The same plugin causes "identified as username" details to get overlayed by the leed icon (see snap 01)
Should be fixed. You have to disable, then remove the code, then reinstall the plugin.


5. When I disable the Fleexed plugin, the "Menu" button does not get clicked (see snap 02)
We don't have this button on the raw theme. Is it from an other plugin?

6. ePub plugin does not work. When enabled, and when I select any option within the plugin, the page refreshes and goes white/blank. There is no error_log entry for this as well, so not sure how to give you any details.
Should be fixed. You have to disable, then remove the code, then reinstall the plugin.


7. The favicon does not load for the deployment. See last snap.
Is it ok without any plugin enabled? Can you check your network calls from the browser, or your server logs to tell me which path is in use on your installation?

**Comment by vdbhb59** [comment] 2023-06-08 04:57
> I'll reply in this thread but it's easier for us that you open a new bug for each question. Plus, it seems like it's mostly "bugs" on https://github.com/Leed-market/fleexed, a long time, not updated theme. Did you try https://github.com/Leed-market/LeedVibes? Kind of the same layout but updated regularly (by myself 😁).
> 
>     1. The URL has a random number always. Example: https://myinstanceurl/#2099 (random number here)
>        It's not a bug, it's a "feature". It's the last item id, used to scroll to the content on mobile.
> 
>     2. The side column loads once and then goes away/vanishes. This happens with Fleexed plugin (see snap 01)
>        Which browser are you using? I can't reproduce this behavior. And you also give your enabled plugins list?
> 
>     3. The same plugin causes "identified as username" details to get overlayed by the leed icon (see snap 01)
>        Should be fixed. You have to disable, then remove the code, then reinstall the plugin.
> 
>     4. When I disable the Fleexed plugin, the "Menu" button does not get clicked (see snap 02)
>        We don't have this button on the raw theme. Is it from an other plugin?
> 
>     5. ePub plugin does not work. When enabled, and when I select any option within the plugin, the page refreshes and goes white/blank. There is no error_log entry for this as well, so not sure how to give you any details.
>        Should be fixed. You have to disable, then remove the code, then reinstall the plugin.
> 
>     6. The favicon does not load for the deployment. See last snap.
>        Is it ok without any plugin enabled? Can you check your network calls from the browser, or your server logs to tell me which path is in use on your installation?

I completely agree, and I usually open individual issue trackers (in any project I use and raise in to). However, I was not sure if these indeed were bugs or some server issues, and most were to do with one plugin itself, so did not break it up as such.

A. I indeed had tried LeedVibes as well, but that too did not work yesterday. I will retry it today.
I usually go 1-by-1 in plugins, check if everything works or not and then move on to the next one. Yesterday, I did the same, and with fleexed it started causing the issues. I have removed all plugins, emptied the 'plugins.states.json' file to give it a clean slate, and will start once more.
1. The random number one I was not aware, and that is my bad. Though now that I searched the code, I could not find from a user perspective (any description), but that is fine, since I am aware of it now. :)
2. I disabled the fleexed, removed it, delete its entry from 'plugins.states.json' file, redownloaded, enabled and it seems working now. I use LibreWolf (hardened) 113.0.2-1.
3. _Overlay seems to be fixed now, but now that I have removed all plugins and will start with a clean slate again in a few hours, I will revert in case of any issues._
4. I am not sure, as there is just one theme, marigold, right? I cannot find any other theme as such. It is not there in the raw theme for sure, but it vanished the moment I removed fleexed. So maybe fleexed has it somewhere?
5. _I will revert for this too in a few hours._
6. No, this still does not work, I cleared everything from everywhere, but the Leed favicon does not load. The server is APACHE latest, path is **/leeds/templates/marigolds**, and the permissions is 0644. The cache states > Unknown (not cached) / 24px × 24px (scaled to 0px × 0px)
See snap:
![image](https://github.com/LeedRSS/Leed/assets/60728004/7c68cf13-3c7c-42ef-954d-820544d37c10)
![image](https://github.com/LeedRSS/Leed/assets/60728004/80d72a29-9a13-4377-bb83-4143eda30548)

**Comment by Simounet** [comment] 2023-06-08 06:49
4. I am not sure, as there is just one theme, marigold, right? I cannot find any other theme as such. It is not there in the raw theme for sure, but it vanished the moment I removed fleexed. So maybe fleexed has it somewhere?

It was the [leedHomeLink](https://github.com/Leed-market/leedHomeLink) plugin.

For the favicon, can you try to access it directly? https://yourdomain.com/PATHTOMYINSTANCE/templates/marigolds/favicon.png

**Comment by vdbhb59** [comment] 2023-06-08 07:03
> 4. I am not sure, as there is just one theme, marigold, right? I cannot find any other theme as such. It is not there in the raw theme for sure, but it vanished the moment I removed fleexed. So maybe fleexed has it somewhere?
> 
> 
> It was the [leedHomeLink](https://github.com/Leed-market/leedHomeLink) plugin.
> 
> For the favicon, can you try to access it directly? https://yourdomain.com/PATHTOMYINSTANCE/templates/marigolds/favicon.png

My bad, I just realized, my hosting has a hotlink option, and that is why I was getting the issue. Apparently other than ICO files, if any favicon is PNG/JPG etc, it does not fetch due to hotlinking protection. I have made exceptions for the same, and it is fine now. :) Sincere apologies, as it got overlooked from my end.

**Comment by Simounet** [comment] 2023-06-08 07:05
No worries mate. Seems like everything is fine now. Can I close this issue?

**Comment by vdbhb59** [comment] 2023-06-08 07:18
Ahh yes, let me close it now. If I have any issues, I will revert. Thanks again for being active and helpful. :)

**Comment by Simounet** [comment] 2023-06-08 07:20
You're welcome. As far as I understand, you're a new Leed user. I'm curious, how did you find us?

**Comment by vdbhb59** [comment] 2023-06-08 07:21
Ohh, sorry have to reopen, as the fleexed issue is still present. :(
![image](https://github.com/LeedRSS/Leed/assets/60728004/19718cd6-60fc-40e0-98c3-f28df1b94a03)

**Comment by Simounet** [comment] 2023-06-08 07:22
Do you have disabled/removed/reinstalled fleexed? Cleared your browser cache?

**Comment by vdbhb59** [comment] 2023-06-08 07:23
> You're welcome. As far as I understand, you're a new Leed user. I'm curious, how did you find us?

Yup, I am a new Leed user, and an OSS fanatic. I host my own instances for many things, for private as well as public stuff. I usually keep searching for awesome open source stuffs, and I searched with RSS/aggregator, etc for I am using FreshRSS and I wanted something different as well, so...

**Comment by Simounet** [comment] 2023-06-08 07:28
No worries! Can I just ask which PHP version do you use?

**Comment by vdbhb59** [comment] 2023-06-08 07:52
> No worries! Can I just ask which PHP version do you use?

Yup. I am using 8.0 for almost all my stuff, and 8.1 for a few of them.

**Comment by Simounet** [comment] 2023-06-08 11:29
For LeedVibes, you shoud try to restart your browser and remove all plugins that can modify the layout (fleexed for example).

For epub, it's a very old code. Never used it but I agree that it should take too long to handle. You can fill in an issue on https://github.com/Leed-market/epub but I can't promise that I will fix it.

**Comment by vdbhb59** [comment] 2023-06-08 12:47
> For LeedVibes, you shoud try to restart your browser and remove all plugins that can modify the layout (fleexed for example).
> 
> For epub, it's a very old code. Never used it but I agree that it should take too long to handle. You can fill in an issue on https://github.com/Leed-market/epub but I can't promise that I will fix it.

Ahh I thought so (timeout). The default theme is much better compared to LeedVibes for me. I prefer the default one. For ePub, I will leave it as it is, since I don't need it as such. I had raised it thinking you may not be aware of it.
BTW, have tried to share your work over on at least 1 place. It is commendable work and very helpful.: -)
https://t.me/FLOSSb0xIN/415
You can close the issue out mate.

**Closed** 2023-06-08 13:21 UTC

**Comment by Simounet** [comment] 2023-06-08 16:30
Perfect and thanks for the sharing message. 😚
